apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: adityashandilya1128/chat-app:auth-service
          ports:
            - containerPort: 4001
          envFrom:
            - configMapRef:
                name: app-config