apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: adityashandilya1128/chat-app:user_service
          ports:
            - containerPort: 4002
          envFrom:
            - configMapRef:
                name: app-config