apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket-service
  template:
    metadata:
      labels:
        app: websocket-service
    spec:
      containers:
        - name: websocket-service
          image: adityashandilya1128/chat-app:ws_service
          ports:
            - containerPort: 4004
          envFrom:
            - configMapRef:
                name: app-config